// Locale variant of /about - ml
// Auto-generated by scripts/generate-locales.js
// Provides localized metadata and passes lang prop to content component

import { default as PageContent } from '../../about/_AboutContent';
import { hreflangAlternates, getMetaForLang, getLocaleDetails } from '@/data/i18n';

const LANG = 'ml';
const LOCALE_PATH = '/ml/about';
const CANONICAL_PATH = '/about';

const localeDetails = getLocaleDetails(LANG);
const meta = getMetaForLang(LANG, 'about');

export const metadata = {
  title: meta.title,
  description: meta.description,
  alternates: { canonical: LOCALE_PATH, languages: hreflangAlternates(CANONICAL_PATH) },
  openGraph: {
    locale: localeDetails.ogLocale,
    url: LOCALE_PATH,
    title: meta.title,
    description: meta.description,
  },
  twitter: {
    title: meta.title,
    description: meta.description,
  },
  robots: { index: true, follow: true },
};

export default function LocalePage() {
  return <PageContent lang={LANG} />;
}
