#!/usr/bin/env node
// Regenerate locale pages with proper lang prop and localized metadata

const fs = require('fs');
const path = require('path');

const LANGUAGES = ['as','bn','gu','hi','kn','kok','ks','ml','mni','mr','or','pa','sat','ta','te','ur'];
// English is default, not in this list for generation (but we include for completeness if needed)

const PAGES = [
  { key: 'home', path: '', file: 'page.js', contentImport: '../_HomeContent', metaKey: 'home' },
  { key: 'about', path: 'about', file: 'about/page.js', contentImport: '../../about/_AboutContent', metaKey: 'about' },
  { key: 'blog', path: 'blog', file: 'blog/page.js', contentImport: '../../blog/_BlogContent', metaKey: 'blog' },
  { key: 'career-certification', path: 'career-certification', file: 'career-certification/page.js', contentImport: '../../career-certification/_CareerCertificationContent', metaKey: 'careerCertification' },
  { key: 'career-counselling', path: 'career-counselling', file: 'career-counselling/page.js', contentImport: '../../career-counselling/_CareerCounsellingContent', metaKey: 'careerCounselling' },
  { key: 'cities', path: 'cities', file: 'cities/page.js', contentImport: '../../cities/_CitiesContent', metaKey: 'cities' },
  { key: 'contact', path: 'contact', file: 'contact/page.js', contentImport: '../../contact/_ContactContent', metaKey: 'contact' },
  { key: 'plan', path: 'plan', file: 'plan/page.js', contentImport: '../../plan/_PlanContent', metaKey: 'plan' },
];

const ROOT = path.join(__dirname, '..');

function getLocaleMeta(lang, pageKey) {
  // We'll use TRANSLATIONS at build time? For generation we fallback to en templates with lang suffix
  // But we inject code that reads from data/i18n at runtime for metadata
  // So we generate metadata that uses getMetaForLang
  return { pageKey, langPath: pageKey === 'home' ? `/${lang}` : `/${lang}/${pageKey === 'home' ? '' : PAGES.find(p=>p.key===pageKey)?.path}` };
}

for (const lang of LANGUAGES) {
  for (const page of PAGES) {
    const dir = path.join(ROOT, 'app', lang, path.dirname(page.file));
    fs.mkdirSync(dir, { recursive: true });
    const filePath = path.join(ROOT, 'app', lang, page.file);

    const localePath = page.key === 'home' ? `/${lang}` : `/${lang}/${page.path}`;
    const canonicalPath = page.path === '' ? '/' : `/${page.path}`;
    const isHome = page.key === 'home';

    // Generate content
    const content = `// Locale variant of /${page.path} - ${lang}
// Auto-generated by scripts/generate-locales.js
// Provides localized metadata and passes lang prop to content component

import { default as PageContent } from '${page.contentImport}';
import { hreflangAlternates, getMetaForLang, getLocaleDetails } from '@/data/i18n';

const LANG = '${lang}';
const LOCALE_PATH = '${localePath}';
const CANONICAL_PATH = '${page.path === '' ? '/' : '/' + page.path}';

const localeDetails = getLocaleDetails(LANG);
const meta = getMetaForLang(LANG, '${page.metaKey}');

export const metadata = {
  title: meta.title,
  description: meta.description,
  alternates: { canonical: LOCALE_PATH, languages: hreflangAlternates(CANONICAL_PATH) },
  openGraph: {
    locale: localeDetails.ogLocale,
    url: LOCALE_PATH,
    title: meta.title,
    description: meta.description,
  },
  twitter: {
    title: meta.title,
    description: meta.description,
  },
  robots: { index: true, follow: true },
};

export default function LocalePage() {
  return <PageContent lang={LANG} />;
}
`;

    fs.writeFileSync(filePath, content);
    console.log(`Wrote ${filePath}`);
  }
}

console.log('Done generating locale pages');
